// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_ACECONScreen_screen_init(void)
{
    ui_ACECONScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ACECONScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton14 = lv_imgbtn_create(ui_ACECONScreen);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowlefticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton14, 240);
    lv_obj_set_width(ui_ImgButton14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton14, -138);
    lv_obj_set_y(ui_ImgButton14, 0);
    lv_obj_set_align(ui_ImgButton14, LV_ALIGN_CENTER);

    ui_LabelOutputs = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelOutputs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutputs, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_LabelOutputs, 0);
    lv_obj_set_y(ui_LabelOutputs, -100);
    lv_obj_set_align(ui_LabelOutputs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOutputs, "ACECON SIGNALS");
    lv_label_set_recolor(ui_LabelOutputs, "true");
    lv_obj_set_style_text_color(ui_LabelOutputs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutputs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOutputs, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelOutputs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelOutputs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelALM = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelALM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelALM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelALM, -77);
    lv_obj_set_y(ui_LabelALM, -60);
    lv_obj_set_align(ui_LabelALM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelALM, "ALM");
    lv_obj_set_style_text_color(ui_LabelALM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelALM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelALM, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelALM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelALM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelALMOff = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelALMOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelALMOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelALMOff, -18);
    lv_obj_set_y(ui_LabelALMOff, -60);
    lv_obj_set_align(ui_LabelALMOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelALMOff, "OFF");
    lv_obj_set_style_text_color(ui_LabelALMOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelALMOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelALMOff, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelALMOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelALMOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelALMOn = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelALMOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelALMOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelALMOn, 75);
    lv_obj_set_y(ui_LabelALMOn, -60);
    lv_obj_set_align(ui_LabelALMOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelALMOn, "ON");
    lv_obj_set_style_text_color(ui_LabelALMOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelALMOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelALMOn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelALMOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelALMOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchALM = lv_switch_create(ui_ACECONScreen);
    lv_obj_set_width(ui_SwitchALM, 50);
    lv_obj_set_height(ui_SwitchALM, 18);
    lv_obj_set_x(ui_SwitchALM, 30);
    lv_obj_set_y(ui_SwitchALM, -60);
    lv_obj_set_align(ui_SwitchALM, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SwitchALM, lv_color_hex(0xFB7E7E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchALM, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchALM, lv_color_hex(0x89F97B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchALM, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_LabelHPS = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelHPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHPS, -76);
    lv_obj_set_y(ui_LabelHPS, -25);
    lv_obj_set_align(ui_LabelHPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHPS, "HPS");
    lv_obj_set_style_text_color(ui_LabelHPS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHPS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelHPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHPSOff = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelHPSOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHPSOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHPSOff, -18);
    lv_obj_set_y(ui_LabelHPSOff, -25);
    lv_obj_set_align(ui_LabelHPSOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHPSOff, "OFF");
    lv_obj_set_style_text_color(ui_LabelHPSOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHPSOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHPSOff, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHPSOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelHPSOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHPSOn = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelHPSOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHPSOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHPSOn, 75);
    lv_obj_set_y(ui_LabelHPSOn, -25);
    lv_obj_set_align(ui_LabelHPSOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHPSOn, "ON");
    lv_obj_set_style_text_color(ui_LabelHPSOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHPSOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHPSOn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHPSOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelHPSOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchHPS = lv_switch_create(ui_ACECONScreen);
    lv_obj_set_width(ui_SwitchHPS, 50);
    lv_obj_set_height(ui_SwitchHPS, 18);
    lv_obj_set_x(ui_SwitchHPS, 30);
    lv_obj_set_y(ui_SwitchHPS, -25);
    lv_obj_set_align(ui_SwitchHPS, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SwitchHPS, lv_color_hex(0xFB7E7E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchHPS, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchHPS, lv_color_hex(0x89F97B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchHPS, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_LabelPPT = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelPPT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPPT, -74);
    lv_obj_set_y(ui_LabelPPT, 10);
    lv_obj_set_align(ui_LabelPPT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPPT, "PPT");
    lv_obj_set_style_text_color(ui_LabelPPT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPPT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPPT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPPTOff = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelPPTOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPTOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPPTOff, -18);
    lv_obj_set_y(ui_LabelPPTOff, 10);
    lv_obj_set_align(ui_LabelPPTOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPPTOff, "OFF");
    lv_obj_set_style_text_color(ui_LabelPPTOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPPTOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPPTOff, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPPTOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPPTOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPPTOn = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelPPTOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPTOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPPTOn, 75);
    lv_obj_set_y(ui_LabelPPTOn, 10);
    lv_obj_set_align(ui_LabelPPTOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPPTOn, "ON");
    lv_obj_set_style_text_color(ui_LabelPPTOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPPTOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPPTOn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPPTOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPPTOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchPPT = lv_switch_create(ui_ACECONScreen);
    lv_obj_set_width(ui_SwitchPPT, 50);
    lv_obj_set_height(ui_SwitchPPT, 18);
    lv_obj_set_x(ui_SwitchPPT, 31);
    lv_obj_set_y(ui_SwitchPPT, 10);
    lv_obj_set_align(ui_SwitchPPT, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SwitchPPT, lv_color_hex(0xFB7E7E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchPPT, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchPPT, lv_color_hex(0x89F97B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchPPT, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_LabelPPS = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelPPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPPS, -75);
    lv_obj_set_y(ui_LabelPPS, 45);
    lv_obj_set_align(ui_LabelPPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPPS, "PPS");
    lv_obj_set_style_text_color(ui_LabelPPS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPPS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchPPS = lv_switch_create(ui_ACECONScreen);
    lv_obj_set_width(ui_SwitchPPS, 50);
    lv_obj_set_height(ui_SwitchPPS, 18);
    lv_obj_set_x(ui_SwitchPPS, 31);
    lv_obj_set_y(ui_SwitchPPS, 45);
    lv_obj_set_align(ui_SwitchPPS, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SwitchPPS, lv_color_hex(0xFB7E7E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchPPS, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchPPS, lv_color_hex(0x89F97B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchPPS, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_LabelPPSOff = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelPPSOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPSOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPPSOff, -18);
    lv_obj_set_y(ui_LabelPPSOff, 45);
    lv_obj_set_align(ui_LabelPPSOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPPSOff, "OFF");
    lv_obj_set_style_text_color(ui_LabelPPSOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPPSOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPPSOff, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPPSOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPPSOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPPSOn = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelPPSOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPSOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPPSOn, 75);
    lv_obj_set_y(ui_LabelPPSOn, 45);
    lv_obj_set_align(ui_LabelPPSOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPPSOn, "ON");
    lv_obj_set_style_text_color(ui_LabelPPSOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPPSOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPPSOn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPPSOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPPSOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIGN = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelIGN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIGN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIGN, -74);
    lv_obj_set_y(ui_LabelIGN, 80);
    lv_obj_set_align(ui_LabelIGN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIGN, "IGN");
    lv_obj_set_style_text_color(ui_LabelIGN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIGN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIGN, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelIGN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelIGN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIGNOff = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelIGNOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIGNOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIGNOff, -18);
    lv_obj_set_y(ui_LabelIGNOff, 80);
    lv_obj_set_align(ui_LabelIGNOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIGNOff, "OFF");
    lv_obj_set_style_text_color(ui_LabelIGNOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIGNOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIGNOff, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelIGNOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelIGNOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIGNOn = lv_label_create(ui_ACECONScreen);
    lv_obj_set_width(ui_LabelIGNOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIGNOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIGNOn, 75);
    lv_obj_set_y(ui_LabelIGNOn, 80);
    lv_obj_set_align(ui_LabelIGNOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIGNOn, "ON");
    lv_obj_set_style_text_color(ui_LabelIGNOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIGNOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIGNOn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelIGNOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelIGNOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchIGN = lv_switch_create(ui_ACECONScreen);
    lv_obj_set_width(ui_SwitchIGN, 50);
    lv_obj_set_height(ui_SwitchIGN, 18);
    lv_obj_set_x(ui_SwitchIGN, 31);
    lv_obj_set_y(ui_SwitchIGN, 80);
    lv_obj_set_align(ui_SwitchIGN, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SwitchIGN, LV_STATE_DISABLED);       /// States

    lv_obj_set_style_bg_color(ui_SwitchIGN, lv_color_hex(0xFB7E7E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchIGN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchIGN, lv_color_hex(0x89F97B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchIGN, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ImgButton1 = lv_imgbtn_create(ui_ACECONScreen);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowrighticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton1, 240);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, 137);
    lv_obj_set_y(ui_ImgButton1, 0);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton14, ui_event_ImgButton14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

}
