// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_MenuScreen1_screen_init(void)
{
    ui_MenuScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonExitMenu1 = lv_imgbtn_create(ui_MenuScreen1);
    lv_imgbtn_set_src(ui_ImgButtonExitMenu1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowlefticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonExitMenu1, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButtonExitMenu1, 240);
    lv_obj_set_width(ui_ImgButtonExitMenu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonExitMenu1, -138);
    lv_obj_set_y(ui_ImgButtonExitMenu1, 0);
    lv_obj_set_align(ui_ImgButtonExitMenu1, LV_ALIGN_CENTER);

    ui_ImgButton3 = lv_imgbtn_create(ui_MenuScreen1);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowrighticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 240);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 137);
    lv_obj_set_y(ui_ImgButton3, 0);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_ImgButton4 = lv_imgbtn_create(ui_MenuScreen1);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowdownicon_png, NULL);
    lv_obj_set_height(ui_ImgButton4, 44);
    lv_obj_set_width(ui_ImgButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton4, 0);
    lv_obj_set_y(ui_ImgButton4, 98);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_LabelAlarmPower = lv_label_create(ui_MenuScreen1);
    lv_obj_set_width(ui_LabelAlarmPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarmPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmPower, -73);
    lv_obj_set_y(ui_LabelAlarmPower, -51);
    lv_obj_set_align(ui_LabelAlarmPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmPower, "Alarm Pwr");
    lv_obj_set_style_text_color(ui_LabelAlarmPower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarmPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarmPower, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAlarmPower, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAlarmPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownAlarmPower = lv_dropdown_create(ui_MenuScreen1);
    lv_dropdown_set_options(ui_DropdownAlarmPower,
                            "Car ON/Car OFF\nCar ON/Man OFF\nMan ON/Man OFF\nNO K9 LEFT BEHIND\nAlways OFF");
    lv_obj_set_width(ui_DropdownAlarmPower, 145);
    lv_obj_set_height(ui_DropdownAlarmPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownAlarmPower, 41);
    lv_obj_set_y(ui_DropdownAlarmPower, -51);
    lv_obj_set_align(ui_DropdownAlarmPower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownAlarmPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownAlarmPower, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DropdownAlarmPower, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DropdownAlarmPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownAlarmPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownAlarmPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownAlarmPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_CheckboxAutoSnooze = lv_checkbox_create(ui_MenuScreen1);
    lv_checkbox_set_text(ui_CheckboxAutoSnooze, "Auto Snooze");
    lv_obj_set_width(ui_CheckboxAutoSnooze, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxAutoSnooze, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxAutoSnooze, -53);
    lv_obj_set_y(ui_CheckboxAutoSnooze, 30);
    lv_obj_set_align(ui_CheckboxAutoSnooze, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxAutoSnooze, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelDoorPower = lv_label_create(ui_MenuScreen1);
    lv_obj_set_width(ui_LabelDoorPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDoorPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDoorPower, -73);
    lv_obj_set_y(ui_LabelDoorPower, -21);
    lv_obj_set_align(ui_LabelDoorPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDoorPower, "Door Pwr");
    lv_obj_set_style_text_color(ui_LabelDoorPower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDoorPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDoorPower, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelDoorPower, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelDoorPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownDoorPower = lv_dropdown_create(ui_MenuScreen1);
    lv_dropdown_set_options(ui_DropdownDoorPower, "Car ON/Car OFF\nCar ON/Man OFF\nMan ON/Man OFF\nAlways OFF");
    lv_obj_set_width(ui_DropdownDoorPower, 145);
    lv_obj_set_height(ui_DropdownDoorPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownDoorPower, 41);
    lv_obj_set_y(ui_DropdownDoorPower, -21);
    lv_obj_set_align(ui_DropdownDoorPower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownDoorPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownDoorPower, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DropdownDoorPower, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DropdownDoorPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownDoorPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownDoorPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownDoorPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_CheckboxStallMonitor = lv_checkbox_create(ui_MenuScreen1);
    lv_checkbox_set_text(ui_CheckboxStallMonitor, "Stall Monitor");
    lv_obj_set_width(ui_CheckboxStallMonitor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStallMonitor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStallMonitor, -53);
    lv_obj_set_y(ui_CheckboxStallMonitor, 57);
    lv_obj_set_align(ui_CheckboxStallMonitor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStallMonitor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelBattVoltSet = lv_label_create(ui_MenuScreen1);
    lv_obj_set_width(ui_LabelBattVoltSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBattVoltSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBattVoltSet, -62);
    lv_obj_set_y(ui_LabelBattVoltSet, 3);
    lv_obj_set_align(ui_LabelBattVoltSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBattVoltSet, "Batt Volt Set");
    lv_obj_set_style_text_color(ui_LabelBattVoltSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBattVoltSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBattVoltSet, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelBattVoltSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelBattVoltSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBattVoltSetValue = lv_label_create(ui_MenuScreen1);
    lv_obj_set_width(ui_LabelBattVoltSetValue, 36);
    lv_obj_set_height(ui_LabelBattVoltSetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBattVoltSetValue, 8);
    lv_obj_set_y(ui_LabelBattVoltSetValue, 3);
    lv_obj_set_align(ui_LabelBattVoltSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBattVoltSetValue, "10.5V");
    lv_obj_set_style_text_align(ui_LabelBattVoltSetValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelBattVoltSetValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelBattVoltSetValue, lv_color_hex(0x37373B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelBattVoltSetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonBattVoltSetDown = lv_imgbtn_create(ui_MenuScreen1);
    lv_imgbtn_set_src(ui_ImgButtonBattVoltSetDown, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowdowniconsmall_png, NULL);
    lv_obj_set_height(ui_ImgButtonBattVoltSetDown, 20);
    lv_obj_set_width(ui_ImgButtonBattVoltSetDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonBattVoltSetDown, 49);
    lv_obj_set_y(ui_ImgButtonBattVoltSetDown, 3);
    lv_obj_set_align(ui_ImgButtonBattVoltSetDown, LV_ALIGN_CENTER);

    ui_ImgButtonBattVoltSetUp = lv_imgbtn_create(ui_MenuScreen1);
    lv_imgbtn_set_src(ui_ImgButtonBattVoltSetUp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupiconsmall_png, NULL);
    lv_obj_set_height(ui_ImgButtonBattVoltSetUp, 20);
    lv_obj_set_width(ui_ImgButtonBattVoltSetUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonBattVoltSetUp, 89);
    lv_obj_set_y(ui_ImgButtonBattVoltSetUp, 3);
    lv_obj_set_align(ui_ImgButtonBattVoltSetUp, LV_ALIGN_CENTER);

    ui_ImgButton16 = lv_imgbtn_create(ui_MenuScreen1);
    lv_imgbtn_set_src(ui_ImgButton16, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupicon_png, NULL);
    lv_obj_set_height(ui_ImgButton16, 44);
    lv_obj_set_width(ui_ImgButton16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton16, 0);
    lv_obj_set_y(ui_ImgButton16, -98);
    lv_obj_set_align(ui_ImgButton16, LV_ALIGN_CENTER);

    ui_CheckboxAuxIn = lv_checkbox_create(ui_MenuScreen1);
    lv_checkbox_set_text(ui_CheckboxAuxIn, "Aux Input");
    lv_obj_set_width(ui_CheckboxAuxIn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxAuxIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxAuxIn, 62);
    lv_obj_set_y(ui_CheckboxAuxIn, 31);
    lv_obj_set_align(ui_CheckboxAuxIn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxAuxIn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_ImgButtonExitMenu1, ui_event_ImgButtonExitMenu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton16, ui_event_ImgButton16, LV_EVENT_ALL, NULL);

}
