// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_MenuScreen4_screen_init(void)
{
    ui_MenuScreen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonExitMenu4 = lv_imgbtn_create(ui_MenuScreen4);
    lv_imgbtn_set_src(ui_ImgButtonExitMenu4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowlefticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonExitMenu4, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButtonExitMenu4, 240);
    lv_obj_set_width(ui_ImgButtonExitMenu4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonExitMenu4, -138);
    lv_obj_set_y(ui_ImgButtonExitMenu4, 0);
    lv_obj_set_align(ui_ImgButtonExitMenu4, LV_ALIGN_CENTER);

    ui_ImgButton17 = lv_imgbtn_create(ui_MenuScreen4);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowrighticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton17, 240);
    lv_obj_set_width(ui_ImgButton17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton17, 137);
    lv_obj_set_y(ui_ImgButton17, 0);
    lv_obj_set_align(ui_ImgButton17, LV_ALIGN_CENTER);

    ui_ImgButton18 = lv_imgbtn_create(ui_MenuScreen4);
    lv_imgbtn_set_src(ui_ImgButton18, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowdownicon_png, NULL);
    lv_obj_set_height(ui_ImgButton18, 44);
    lv_obj_set_width(ui_ImgButton18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton18, 0);
    lv_obj_set_y(ui_ImgButton18, 98);
    lv_obj_set_align(ui_ImgButton18, LV_ALIGN_CENTER);

    ui_ImgButton19 = lv_imgbtn_create(ui_MenuScreen4);
    lv_imgbtn_set_src(ui_ImgButton19, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupicon_png, NULL);
    lv_obj_set_height(ui_ImgButton19, 44);
    lv_obj_set_width(ui_ImgButton19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton19, 0);
    lv_obj_set_y(ui_ImgButton19, -98);
    lv_obj_set_align(ui_ImgButton19, LV_ALIGN_CENTER);

    ui_ButtonAutoTest = lv_btn_create(ui_MenuScreen4);
    lv_obj_set_width(ui_ButtonAutoTest, 175);
    lv_obj_set_height(ui_ButtonAutoTest, 39);
    lv_obj_set_align(ui_ButtonAutoTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAutoTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAutoTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAutoTest, lv_color_hex(0xCACA05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAutoTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_MenuScreen4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Begin Auto Test");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xCA0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonExitMenu4, ui_event_ImgButtonExitMenu4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton17, ui_event_ImgButton17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton18, ui_event_ImgButton18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton19, ui_event_ImgButton19, LV_EVENT_ALL, NULL);

}
