// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_MenuScreen2_screen_init(void)
{
    ui_MenuScreen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonExitMenu2 = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButtonExitMenu2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowlefticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonExitMenu2, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButtonExitMenu2, 240);
    lv_obj_set_width(ui_ImgButtonExitMenu2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonExitMenu2, -138);
    lv_obj_set_y(ui_ImgButtonExitMenu2, 0);
    lv_obj_set_align(ui_ImgButtonExitMenu2, LV_ALIGN_CENTER);

    ui_ImgButton8 = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowrighticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton8, 240);
    lv_obj_set_width(ui_ImgButton8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton8, 137);
    lv_obj_set_y(ui_ImgButton8, 0);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    ui_ImgButton12 = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowdownicon_png, NULL);
    lv_obj_set_height(ui_ImgButton12, 44);
    lv_obj_set_width(ui_ImgButton12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton12, 0);
    lv_obj_set_y(ui_ImgButton12, 98);
    lv_obj_set_align(ui_ImgButton12, LV_ALIGN_CENTER);

    ui_LabelAlarmHotSet = lv_label_create(ui_MenuScreen2);
    lv_obj_set_width(ui_LabelAlarmHotSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarmHotSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmHotSet, -62);
    lv_obj_set_y(ui_LabelAlarmHotSet, -54);
    lv_obj_set_align(ui_LabelAlarmHotSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmHotSet, "Alarm Hot Set");
    lv_obj_set_style_text_color(ui_LabelAlarmHotSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarmHotSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarmHotSet, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAlarmHotSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAlarmHotSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlarmHotSetValue = lv_label_create(ui_MenuScreen2);
    lv_obj_set_width(ui_LabelAlarmHotSetValue, 35);
    lv_obj_set_height(ui_LabelAlarmHotSetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmHotSetValue, 15);
    lv_obj_set_y(ui_LabelAlarmHotSetValue, -54);
    lv_obj_set_align(ui_LabelAlarmHotSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmHotSetValue, "77F");
    lv_obj_set_style_text_align(ui_LabelAlarmHotSetValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelAlarmHotSetValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAlarmHotSetValue, lv_color_hex(0x37373B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAlarmHotSetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonHotSetDown = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButtonHotSetDown, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowdowniconsmall_png, NULL);
    lv_obj_set_height(ui_ImgButtonHotSetDown, 20);
    lv_obj_set_width(ui_ImgButtonHotSetDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonHotSetDown, 52);
    lv_obj_set_y(ui_ImgButtonHotSetDown, -54);
    lv_obj_set_align(ui_ImgButtonHotSetDown, LV_ALIGN_CENTER);

    ui_ImgButtonHotSetUp = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButtonHotSetUp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupiconsmall_png, NULL);
    lv_obj_set_height(ui_ImgButtonHotSetUp, 20);
    lv_obj_set_width(ui_ImgButtonHotSetUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonHotSetUp, 92);
    lv_obj_set_y(ui_ImgButtonHotSetUp, -54);
    lv_obj_set_align(ui_ImgButtonHotSetUp, LV_ALIGN_CENTER);

    ui_LabelAlarmColdSet = lv_label_create(ui_MenuScreen2);
    lv_obj_set_width(ui_LabelAlarmColdSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarmColdSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmColdSet, -59);
    lv_obj_set_y(ui_LabelAlarmColdSet, -16);
    lv_obj_set_align(ui_LabelAlarmColdSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmColdSet, "Alarm Cold Set");
    lv_obj_set_style_text_color(ui_LabelAlarmColdSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarmColdSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarmColdSet, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAlarmColdSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAlarmColdSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlarmColdSetValue = lv_label_create(ui_MenuScreen2);
    lv_obj_set_width(ui_LabelAlarmColdSetValue, 35);
    lv_obj_set_height(ui_LabelAlarmColdSetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmColdSetValue, 15);
    lv_obj_set_y(ui_LabelAlarmColdSetValue, -16);
    lv_obj_set_align(ui_LabelAlarmColdSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmColdSetValue, "-12C");
    lv_obj_set_style_text_align(ui_LabelAlarmColdSetValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelAlarmColdSetValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAlarmColdSetValue, lv_color_hex(0x37373B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAlarmColdSetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonColdSetDown = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButtonColdSetDown, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowdowniconsmall_png, NULL);
    lv_obj_set_height(ui_ImgButtonColdSetDown, 20);
    lv_obj_set_width(ui_ImgButtonColdSetDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonColdSetDown, 52);
    lv_obj_set_y(ui_ImgButtonColdSetDown, -16);
    lv_obj_set_align(ui_ImgButtonColdSetDown, LV_ALIGN_CENTER);

    ui_ImgButtonColdSetUp = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButtonColdSetUp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupiconsmall_png, NULL);
    lv_obj_set_height(ui_ImgButtonColdSetUp, 20);
    lv_obj_set_width(ui_ImgButtonColdSetUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonColdSetUp, 92);
    lv_obj_set_y(ui_ImgButtonColdSetUp, -16);
    lv_obj_set_align(ui_ImgButtonColdSetUp, LV_ALIGN_CENTER);

    ui_CheckboxTemperatureAveraging = lv_checkbox_create(ui_MenuScreen2);
    lv_checkbox_set_text(ui_CheckboxTemperatureAveraging, "Temp Averaging");
    lv_obj_set_width(ui_CheckboxTemperatureAveraging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxTemperatureAveraging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxTemperatureAveraging, -32);
    lv_obj_set_y(ui_CheckboxTemperatureAveraging, 49);
    lv_obj_set_align(ui_CheckboxTemperatureAveraging, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxTemperatureAveraging, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_DropdownTempUnits = lv_dropdown_create(ui_MenuScreen2);
    lv_dropdown_set_options(ui_DropdownTempUnits, "F\nC");
    lv_obj_set_width(ui_DropdownTempUnits, 30);
    lv_obj_set_height(ui_DropdownTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownTempUnits, 22);
    lv_obj_set_y(ui_DropdownTempUnits, 17);
    lv_obj_set_align(ui_DropdownTempUnits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTempUnits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_align(ui_DropdownTempUnits, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownTempUnits, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DropdownTempUnits, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DropdownTempUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownTempUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownTempUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownTempUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelTempUnits = lv_label_create(ui_MenuScreen2);
    lv_obj_set_width(ui_LabelTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempUnits, -58);
    lv_obj_set_y(ui_LabelTempUnits, 16);
    lv_obj_set_align(ui_LabelTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempUnits, "Temp C or F");
    lv_obj_set_style_text_color(ui_LabelTempUnits, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempUnits, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelTempUnits, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelTempUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton13 = lv_imgbtn_create(ui_MenuScreen2);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowupicon_png, NULL);
    lv_obj_set_height(ui_ImgButton13, 44);
    lv_obj_set_width(ui_ImgButton13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton13, 0);
    lv_obj_set_y(ui_ImgButton13, -98);
    lv_obj_set_align(ui_ImgButton13, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButtonExitMenu2, ui_event_ImgButtonExitMenu2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton12, ui_event_ImgButton12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton13, ui_event_ImgButton13, LV_EVENT_ALL, NULL);

}
