// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_MenuHelpScreen_screen_init(void)
{
    ui_MenuHelpScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuHelpScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuHelpTextArea = lv_textarea_create(ui_MenuHelpScreen);
    lv_obj_set_width(ui_MenuHelpTextArea, 222);
    lv_obj_set_height(ui_MenuHelpTextArea, 70);
    lv_obj_set_x(ui_MenuHelpTextArea, 4);
    lv_obj_set_y(ui_MenuHelpTextArea, 1);
    lv_obj_set_align(ui_MenuHelpTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_MenuHelpTextArea, "B1 Menu Help State");
    lv_textarea_set_placeholder_text(ui_MenuHelpTextArea, "Placeholder...");



}
