// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_NoK9Screen_screen_init(void)
{
    ui_NoK9Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_NoK9Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoK9TextArea = lv_textarea_create(ui_NoK9Screen);
    lv_obj_set_width(ui_NoK9TextArea, 222);
    lv_obj_set_height(ui_NoK9TextArea, 70);
    lv_obj_set_x(ui_NoK9TextArea, 4);
    lv_obj_set_y(ui_NoK9TextArea, 1);
    lv_obj_set_align(ui_NoK9TextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_NoK9TextArea, "No K9 Screen");
    lv_textarea_set_placeholder_text(ui_NoK9TextArea, "Placeholder...");



}
