// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_OperationScreen_screen_init(void)
{
    ui_OperationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OperationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton7 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowlefticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton7, 240);
    lv_obj_set_width(ui_ImgButton7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton7, -137);
    lv_obj_set_y(ui_ImgButton7, 0);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ImgButton7, LV_STATE_DISABLED);       /// States

    ui_ImgButtonBattery = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonBattery, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_batteryenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonBattery, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_batterydisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonBattery, 45);
    lv_obj_set_width(ui_ImgButtonBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonBattery, -90);
    lv_obj_set_y(ui_ImgButtonBattery, -95);
    lv_obj_set_align(ui_ImgButtonBattery, LV_ALIGN_CENTER);

    ui_ImgButtonDoorClosed = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonDoorClosed, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cardoorenabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonDoorClosed, 45);
    lv_obj_set_width(ui_ImgButtonDoorClosed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonDoorClosed, -45);
    lv_obj_set_y(ui_ImgButtonDoorClosed, -95);
    lv_obj_set_align(ui_ImgButtonDoorClosed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonDoorClosed, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgButtonDoorClosed, lv_color_hex(0xA30000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_img_recolor_opa(ui_ImgButtonDoorClosed, 0, LV_PART_MAIN | LV_STATE_USER_1);

    ui_ImgButtonDoorOpen = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonDoorOpen, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cardooropenicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonDoorOpen, 45);
    lv_obj_set_width(ui_ImgButtonDoorOpen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonDoorOpen, -45);
    lv_obj_set_y(ui_ImgButtonDoorOpen, -95);
    lv_obj_set_align(ui_ImgButtonDoorOpen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonDoorOpen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ImgButtonDoorOpen, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgButtonDoorOpen, lv_color_hex(0xA30000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_img_recolor_opa(ui_ImgButtonDoorOpen, 0, LV_PART_MAIN | LV_STATE_USER_1);

    ui_ImgButtonDoorPopped = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonDoorPopped, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cardoorpoppedicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonDoorPopped, 45);
    lv_obj_set_width(ui_ImgButtonDoorPopped, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonDoorPopped, -45);
    lv_obj_set_y(ui_ImgButtonDoorPopped, -95);
    lv_obj_set_align(ui_ImgButtonDoorPopped, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonDoorPopped, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ImgButtonDoorPopped, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgButtonDoorPopped, lv_color_hex(0xA30000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_img_recolor_opa(ui_ImgButtonDoorPopped, 0, LV_PART_MAIN | LV_STATE_USER_1);

    ui_ImgButtonDoorDisabled = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonDoorDisabled, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cardoordisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonDoorDisabled, 45);
    lv_obj_set_width(ui_ImgButtonDoorDisabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonDoorDisabled, -45);
    lv_obj_set_y(ui_ImgButtonDoorDisabled, -95);
    lv_obj_set_align(ui_ImgButtonDoorDisabled, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonDoorDisabled, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ImgButtonDoorDisabled, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgButtonDoorDisabled, lv_color_hex(0xA30000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_img_recolor_opa(ui_ImgButtonDoorDisabled, 0, LV_PART_MAIN | LV_STATE_USER_1);

    ui_ImgButtonKey = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonKey, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_keyenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonKey, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_keyicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonKey, 45);
    lv_obj_set_width(ui_ImgButtonKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonKey, 0);
    lv_obj_set_y(ui_ImgButtonKey, -95);
    lv_obj_set_align(ui_ImgButtonKey, LV_ALIGN_CENTER);

    ui_ImgButtonEngine = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonEngine, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_engineenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonEngine, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_enginedisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonEngine, 45);
    lv_obj_set_width(ui_ImgButtonEngine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonEngine, 44);
    lv_obj_set_y(ui_ImgButtonEngine, -95);
    lv_obj_set_align(ui_ImgButtonEngine, LV_ALIGN_CENTER);

    ui_ImgButtonWiFi0 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonWiFi0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_0_png, NULL);
    lv_obj_set_height(ui_ImgButtonWiFi0, 45);
    lv_obj_set_width(ui_ImgButtonWiFi0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonWiFi0, 89);
    lv_obj_set_y(ui_ImgButtonWiFi0, -95);
    lv_obj_set_align(ui_ImgButtonWiFi0, LV_ALIGN_CENTER);

    ui_ImgButtonWiFi1 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonWiFi1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_1_png, NULL);
    lv_obj_set_height(ui_ImgButtonWiFi1, 45);
    lv_obj_set_width(ui_ImgButtonWiFi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonWiFi1, 89);
    lv_obj_set_y(ui_ImgButtonWiFi1, -95);
    lv_obj_set_align(ui_ImgButtonWiFi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonWiFi1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ImgButtonWiFi2 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonWiFi2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_2_png, NULL);
    lv_obj_set_height(ui_ImgButtonWiFi2, 45);
    lv_obj_set_width(ui_ImgButtonWiFi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonWiFi2, 89);
    lv_obj_set_y(ui_ImgButtonWiFi2, -95);
    lv_obj_set_align(ui_ImgButtonWiFi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonWiFi2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ImgButtonWiFi3 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonWiFi3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_3_png, NULL);
    lv_obj_set_height(ui_ImgButtonWiFi3, 45);
    lv_obj_set_width(ui_ImgButtonWiFi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonWiFi3, 89);
    lv_obj_set_y(ui_ImgButtonWiFi3, -95);
    lv_obj_set_align(ui_ImgButtonWiFi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonWiFi3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ImgButtonWiFi4 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonWiFi4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_4_png, NULL);
    lv_obj_set_height(ui_ImgButtonWiFi4, 45);
    lv_obj_set_width(ui_ImgButtonWiFi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonWiFi4, 89);
    lv_obj_set_y(ui_ImgButtonWiFi4, -95);
    lv_obj_set_align(ui_ImgButtonWiFi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButtonWiFi4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_BtnSnooze = lv_btn_create(ui_OperationScreen);
    lv_obj_set_width(ui_BtnSnooze, 148);
    lv_obj_set_height(ui_BtnSnooze, 26);
    lv_obj_set_x(ui_BtnSnooze, 0);
    lv_obj_set_y(ui_BtnSnooze, -20);
    lv_obj_set_align(ui_BtnSnooze, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSnooze, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSnooze, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSnooze, lv_color_hex(0xFFFA29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSnooze, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlarmText = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelAlarmText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarmText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmText, -29);
    lv_obj_set_y(ui_LabelAlarmText, -46);
    lv_obj_set_align(ui_LabelAlarmText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmText, "SNOOZING");
    lv_obj_set_style_text_color(ui_LabelAlarmText, lv_color_hex(0xC2000D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarmText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarmText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlarmCounter = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelAlarmCounter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarmCounter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmCounter, 65);
    lv_obj_set_y(ui_LabelAlarmCounter, -46);
    lv_obj_set_align(ui_LabelAlarmCounter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmCounter, "99:99");
    lv_obj_set_style_text_color(ui_LabelAlarmCounter, lv_color_hex(0xC2000D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarmCounter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarmCounter, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLeftTemp = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelLeftTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLeftTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLeftTemp, -86);
    lv_obj_set_y(ui_LabelLeftTemp, 45);
    lv_obj_set_align(ui_LabelLeftTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLeftTemp, "---");
    lv_obj_set_style_text_font(ui_LabelLeftTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRightTemp = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelRightTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRightTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRightTemp, 88);
    lv_obj_set_y(ui_LabelRightTemp, 45);
    lv_obj_set_align(ui_LabelRightTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRightTemp, "---");
    lv_obj_set_style_text_font(ui_LabelRightTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempAvg = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelTempAvg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempAvg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempAvg, 0);
    lv_obj_set_y(ui_LabelTempAvg, 34);
    lv_obj_set_align(ui_LabelTempAvg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempAvg, "---");
    lv_obj_set_style_text_font(ui_LabelTempAvg, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonEnterMenu1 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonEnterMenu1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowrighticon_png, NULL);
    lv_obj_set_height(ui_ImgButtonEnterMenu1, 240);
    lv_obj_set_width(ui_ImgButtonEnterMenu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonEnterMenu1, 137);
    lv_obj_set_y(ui_ImgButtonEnterMenu1, 0);
    lv_obj_set_align(ui_ImgButtonEnterMenu1, LV_ALIGN_CENTER);

    ui_LabelAlarmTextExtra = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelAlarmTextExtra, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarmTextExtra, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlarmTextExtra, 0);
    lv_obj_set_y(ui_LabelAlarmTextExtra, -20);
    lv_obj_set_align(ui_LabelAlarmTextExtra, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarmTextExtra, "SNOOZE  9/9");
    lv_obj_set_style_text_color(ui_LabelAlarmTextExtra, lv_color_hex(0xC2000D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarmTextExtra, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarmTextExtra, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonEnterMenu1, ui_event_ImgButtonEnterMenu1, LV_EVENT_ALL, NULL);

}
