// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_OperationScreen_screen_init(void)
{
    ui_OperationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OperationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton7 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowlefticon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_arrowiconblank_png, NULL);
    lv_obj_set_height(ui_ImgButton7, 240);
    lv_obj_set_width(ui_ImgButton7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton7, -137);
    lv_obj_set_y(ui_ImgButton7, 0);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ImgButton7, LV_STATE_DISABLED);       /// States

    ui_ImgButtonBattery = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonBattery, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_batteryenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonBattery, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_batterydisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonBattery, 45);
    lv_obj_set_width(ui_ImgButtonBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonBattery, -90);
    lv_obj_set_y(ui_ImgButtonBattery, -95);
    lv_obj_set_align(ui_ImgButtonBattery, LV_ALIGN_CENTER);

    ui_ImgButtonDoor = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonDoor, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cardoorenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonDoor, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cardooropenicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonDoor, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_cardoordisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonDoor, 45);
    lv_obj_set_width(ui_ImgButtonDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonDoor, -45);
    lv_obj_set_y(ui_ImgButtonDoor, -95);
    lv_obj_set_align(ui_ImgButtonDoor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButtonDoor, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgButtonDoor, lv_color_hex(0xA30000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_img_recolor_opa(ui_ImgButtonDoor, 0, LV_PART_MAIN | LV_STATE_USER_1);

    ui_ImgButtonKey = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonKey, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_keyenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonKey, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_keyicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonKey, 45);
    lv_obj_set_width(ui_ImgButtonKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonKey, 0);
    lv_obj_set_y(ui_ImgButtonKey, -95);
    lv_obj_set_align(ui_ImgButtonKey, LV_ALIGN_CENTER);

    ui_ImgButtonEngine = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonEngine, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_engineenabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonEngine, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_enginedisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonEngine, 45);
    lv_obj_set_width(ui_ImgButtonEngine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonEngine, 44);
    lv_obj_set_y(ui_ImgButtonEngine, -95);
    lv_obj_set_align(ui_ImgButtonEngine, LV_ALIGN_CENTER);

    ui_ImgButtonWiFi = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButtonWiFi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifienabledicon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonWiFi, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_wifidisabledicon_png, NULL);
    lv_obj_set_height(ui_ImgButtonWiFi, 45);
    lv_obj_set_width(ui_ImgButtonWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonWiFi, 89);
    lv_obj_set_y(ui_ImgButtonWiFi, -95);
    lv_obj_set_align(ui_ImgButtonWiFi, LV_ALIGN_CENTER);

    ui_ImgTempCircle = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgTempCircle, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_greentempcircle_png, NULL);
    lv_imgbtn_set_src(ui_ImgTempCircle, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_redtempcircle_png, NULL);
    lv_obj_set_height(ui_ImgTempCircle, 135);
    lv_obj_set_width(ui_ImgTempCircle, LV_SIZE_CONTENT);   /// 133
    lv_obj_set_x(ui_ImgTempCircle, 0);
    lv_obj_set_y(ui_ImgTempCircle, 34);
    lv_obj_set_align(ui_ImgTempCircle, LV_ALIGN_CENTER);

    ui_LabelLeftTemp = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelLeftTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLeftTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLeftTemp, -86);
    lv_obj_set_y(ui_LabelLeftTemp, 45);
    lv_obj_set_align(ui_LabelLeftTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLeftTemp, "-12.0");

    ui_LabelRightTemp = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelRightTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRightTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRightTemp, 88);
    lv_obj_set_y(ui_LabelRightTemp, 45);
    lv_obj_set_align(ui_LabelRightTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRightTemp, "95.0");

    ui_LabelTempAvg = lv_label_create(ui_OperationScreen);
    lv_obj_set_width(ui_LabelTempAvg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempAvg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempAvg, 0);
    lv_obj_set_y(ui_LabelTempAvg, 34);
    lv_obj_set_align(ui_LabelTempAvg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempAvg, "41.5");

    ui_ImgButton6 = lv_imgbtn_create(ui_OperationScreen);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowrighticon_png, NULL);
    lv_obj_set_height(ui_ImgButton6, 240);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton6, 137);
    lv_obj_set_y(ui_ImgButton6, 0);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);

}
