// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_PowerDownScreen_screen_init(void)
{
    ui_PowerDownScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PowerDownScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerDownTextArea = lv_textarea_create(ui_PowerDownScreen);
    lv_obj_set_width(ui_PowerDownTextArea, 222);
    lv_obj_set_height(ui_PowerDownTextArea, 70);
    lv_obj_set_x(ui_PowerDownTextArea, 4);
    lv_obj_set_y(ui_PowerDownTextArea, 1);
    lv_obj_set_align(ui_PowerDownTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PowerDownTextArea, "Power Down");
    lv_textarea_set_placeholder_text(ui_PowerDownTextArea, "Placeholder...");



}
