// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_PowerAppliedScreen_screen_init(void)
{
    ui_PowerAppliedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PowerAppliedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_PowerAppliedScreen);
    lv_img_set_src(ui_Image4, &ui_img_acek9logo_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, -74);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPowerAppliedScreen = lv_label_create(ui_PowerAppliedScreen);
    lv_obj_set_width(ui_LabelPowerAppliedScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPowerAppliedScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPowerAppliedScreen, 0);
    lv_obj_set_y(ui_LabelPowerAppliedScreen, 14);
    lv_obj_set_align(ui_LabelPowerAppliedScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPowerAppliedScreen, "Power Applied to Control Head");

}
