// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_PowerAppliedScreen_screen_init(void)
{
    ui_PowerAppliedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PowerAppliedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerAppliedTextArea = lv_textarea_create(ui_PowerAppliedScreen);
    lv_obj_set_width(ui_PowerAppliedTextArea, 222);
    lv_obj_set_height(ui_PowerAppliedTextArea, 70);
    lv_obj_set_x(ui_PowerAppliedTextArea, 4);
    lv_obj_set_y(ui_PowerAppliedTextArea, 1);
    lv_obj_set_align(ui_PowerAppliedTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PowerAppliedTextArea, "A1_POWERAPPLIED_STATE");
    lv_textarea_set_placeholder_text(ui_PowerAppliedTextArea, "Placeholder...");



}
