// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_PowerOffScreen_screen_init(void)
{
    ui_PowerOffScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PowerOffScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerOffTextArea = lv_textarea_create(ui_PowerOffScreen);
    lv_obj_set_width(ui_PowerOffTextArea, 150);
    lv_obj_set_height(ui_PowerOffTextArea, 70);
    lv_obj_set_x(ui_PowerOffTextArea, 4);
    lv_obj_set_y(ui_PowerOffTextArea, 1);
    lv_obj_set_align(ui_PowerOffTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PowerOffTextArea, "A0_OFF_STATE");
    lv_textarea_set_placeholder_text(ui_PowerOffTextArea, "Placeholder...");



}
