// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "../ui.h"

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSpashScreenBackground = lv_imgbtn_create(ui_SplashScreen);
    lv_imgbtn_set_src(ui_btnSpashScreenBackground, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_acek9logo_png, NULL);
    lv_imgbtn_set_src(ui_btnSpashScreenBackground, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_acek9logo_png, NULL);
    lv_imgbtn_set_src(ui_btnSpashScreenBackground, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_acek9logo_png, NULL);
    lv_obj_set_width(ui_btnSpashScreenBackground, 243);
    lv_obj_set_height(ui_btnSpashScreenBackground, 108);
    lv_obj_set_x(ui_btnSpashScreenBackground, -6);
    lv_obj_set_y(ui_btnSpashScreenBackground, lv_pct(1));
    lv_obj_set_align(ui_btnSpashScreenBackground, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_btnSpashScreenBackground, ui_event_btnSpashScreenBackground, LV_EVENT_ALL, NULL);

}
