// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t * ui_SplashScreen;
void ui_event_btnSpashScreenBackground(lv_event_t * e);
lv_obj_t * ui_btnSpashScreenBackground;


// SCREEN: ui_OperationScreen
void ui_OperationScreen_screen_init(void);
lv_obj_t * ui_OperationScreen;
lv_obj_t * ui_ImgButton7;
lv_obj_t * ui_ImgButtonBattery;
lv_obj_t * ui_ImgButtonDoor;
lv_obj_t * ui_ImgButtonKey;
lv_obj_t * ui_ImgButtonEngine;
lv_obj_t * ui_ImgButtonWiFi;
lv_obj_t * ui_ImgTempCircle;
lv_obj_t * ui_LabelLeftTemp;
lv_obj_t * ui_LabelRightTemp;
lv_obj_t * ui_LabelTempAvg;
void ui_event_ImgButton6(lv_event_t * e);
lv_obj_t * ui_ImgButton6;


// SCREEN: ui_ACECONScreen
void ui_ACECONScreen_screen_init(void);
lv_obj_t * ui_ACECONScreen;
void ui_event_ImgButton14(lv_event_t * e);
lv_obj_t * ui_ImgButton14;
lv_obj_t * ui_LabelOutputs;
lv_obj_t * ui_LabelALM;
lv_obj_t * ui_LabelALMOff;
lv_obj_t * ui_LabelALMOn;
lv_obj_t * ui_SwitchALM;
lv_obj_t * ui_LabelHPS;
lv_obj_t * ui_LabelHPSOff;
lv_obj_t * ui_LabelHPSOn;
lv_obj_t * ui_SwitchHPS;
lv_obj_t * ui_LabelPPT;
lv_obj_t * ui_LabelPPTOff;
lv_obj_t * ui_LabelPPTOn;
lv_obj_t * ui_SwitchPPT;
lv_obj_t * ui_LabelPPS;
lv_obj_t * ui_SwitchPPS;
lv_obj_t * ui_LabelPPSOff;
lv_obj_t * ui_LabelPPSOn;
lv_obj_t * ui_LabelIGN;
lv_obj_t * ui_LabelIGNOff;
lv_obj_t * ui_LabelIGNOn;
lv_obj_t * ui_SwitchIGN;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;


// SCREEN: ui_ACEDATAScreen
void ui_ACEDATAScreen_screen_init(void);
lv_obj_t * ui_ACEDATAScreen;
lv_obj_t * ui_LabelOutputs1;
void ui_event_ImgButton9(lv_event_t * e);
lv_obj_t * ui_ImgButton9;
lv_obj_t * ui_LabelTemp1;
lv_obj_t * ui_LabelTemp1Val;
lv_obj_t * ui_LabelTemp2;
lv_obj_t * ui_LabelTemp2Val;
lv_obj_t * ui_LabelBattery;
lv_obj_t * ui_LabelBatteryVal;
lv_obj_t * ui_LabelEngineStatus;
lv_obj_t * ui_LabelEngineStatusVal;
lv_obj_t * ui_LabelEngineStallSensor;
lv_obj_t * ui_LabelEngineStallSensorVal;
lv_obj_t * ui_LabelEngineStallCount;
lv_obj_t * ui_LabelEngineStallCountVal;
lv_obj_t * ui_LabelAux1;
lv_obj_t * ui_LabelAux1Val;
lv_obj_t * ui_LabelAux2;
lv_obj_t * ui_LabelAux2Val;
lv_obj_t * ui_LabelK9Doors;
lv_obj_t * ui_LabelK9DoorsVal;
lv_obj_t * ui_LabelVIMModel;
lv_obj_t * ui_LabelVIMModelVal;
void ui_event_ImgButton10(lv_event_t * e);
lv_obj_t * ui_ImgButton10;


// SCREEN: ui_SerialCOMsScreen
void ui_SerialCOMsScreen_screen_init(void);
lv_obj_t * ui_SerialCOMsScreen;
lv_obj_t * ui_LabelTXData;
lv_obj_t * ui_TextAreaTXData;
lv_obj_t * ui_LabelRXData;
lv_obj_t * ui_TextAreaRXData;
void ui_event_ImgButton11(lv_event_t * e);
lv_obj_t * ui_ImgButton11;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnSpashScreenBackground(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACEDATAScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACEDATAScreen_screen_init);
    }
}
void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SerialCOMsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SerialCOMsScreen_screen_init);
    }
}
void ui_event_ImgButton11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACEDATAScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ACEDATAScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_OperationScreen_screen_init();
    ui_ACECONScreen_screen_init();
    ui_ACEDATAScreen_screen_init();
    ui_SerialCOMsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
