// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t * ui_SplashScreen;
void ui_event_btnSpashScreenBackground(lv_event_t * e);
lv_obj_t * ui_btnSpashScreenBackground;


// SCREEN: ui_OperationScreen
void ui_OperationScreen_screen_init(void);
lv_obj_t * ui_OperationScreen;
lv_obj_t * ui_ImgButton7;
lv_obj_t * ui_ImgButtonBattery;
lv_obj_t * ui_ImgButtonDoorClosed;
lv_obj_t * ui_ImgButtonDoorOpen;
lv_obj_t * ui_ImgButtonDoorPopped;
lv_obj_t * ui_ImgButtonDoorDisabled;
lv_obj_t * ui_ImgButtonKey;
lv_obj_t * ui_ImgButtonEngine;
lv_obj_t * ui_ImgButtonWiFi0;
lv_obj_t * ui_ImgButtonWiFi1;
lv_obj_t * ui_ImgButtonWiFi2;
lv_obj_t * ui_ImgButtonWiFi3;
lv_obj_t * ui_ImgButtonWiFi4;
lv_obj_t * ui_BtnSnooze;
lv_obj_t * ui_LabelAlarmText;
lv_obj_t * ui_LabelAlarmCounter;
lv_obj_t * ui_LabelLeftTemp;
lv_obj_t * ui_LabelRightTemp;
lv_obj_t * ui_LabelTempAvg;
void ui_event_ImgButtonEnterMenu1(lv_event_t * e);
lv_obj_t * ui_ImgButtonEnterMenu1;
lv_obj_t * ui_LabelAlarmTextExtra;


// SCREEN: ui_MenuScreen1
void ui_MenuScreen1_screen_init(void);
lv_obj_t * ui_MenuScreen1;
void ui_event_ImgButtonExitMenu1(lv_event_t * e);
lv_obj_t * ui_ImgButtonExitMenu1;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
void ui_event_ImgButton4(lv_event_t * e);
lv_obj_t * ui_ImgButton4;
lv_obj_t * ui_LabelAlarmPower;
lv_obj_t * ui_DropdownAlarmPower;
lv_obj_t * ui_CheckboxAutoSnooze;
lv_obj_t * ui_LabelDoorPower;
lv_obj_t * ui_DropdownDoorPower;
lv_obj_t * ui_CheckboxStallMonitor;
lv_obj_t * ui_LabelBattVoltSet;
lv_obj_t * ui_LabelBattVoltSetValue;
lv_obj_t * ui_ImgButtonBattVoltSetDown;
lv_obj_t * ui_ImgButtonBattVoltSetUp;
void ui_event_ImgButton16(lv_event_t * e);
lv_obj_t * ui_ImgButton16;
lv_obj_t * ui_CheckboxAuxIn;


// SCREEN: ui_MenuScreen2
void ui_MenuScreen2_screen_init(void);
lv_obj_t * ui_MenuScreen2;
void ui_event_ImgButtonExitMenu2(lv_event_t * e);
lv_obj_t * ui_ImgButtonExitMenu2;
void ui_event_ImgButton8(lv_event_t * e);
lv_obj_t * ui_ImgButton8;
void ui_event_ImgButton12(lv_event_t * e);
lv_obj_t * ui_ImgButton12;
lv_obj_t * ui_LabelAlarmHotSet;
lv_obj_t * ui_LabelAlarmHotSetValue;
lv_obj_t * ui_ImgButtonHotSetDown;
lv_obj_t * ui_ImgButtonHotSetUp;
lv_obj_t * ui_LabelAlarmColdSet;
lv_obj_t * ui_LabelAlarmColdSetValue;
lv_obj_t * ui_ImgButtonColdSetDown;
lv_obj_t * ui_ImgButtonColdSetUp;
lv_obj_t * ui_CheckboxTemperatureAveraging;
lv_obj_t * ui_DropdownTempUnits;
lv_obj_t * ui_LabelTempUnits;
void ui_event_ImgButton13(lv_event_t * e);
lv_obj_t * ui_ImgButton13;


// SCREEN: ui_MenuScreen3
void ui_MenuScreen3_screen_init(void);
lv_obj_t * ui_MenuScreen3;
void ui_event_ImgButtonExitMenu3(lv_event_t * e);
lv_obj_t * ui_ImgButtonExitMenu3;
void ui_event_ImgButton21(lv_event_t * e);
lv_obj_t * ui_ImgButton21;
void ui_event_ImgButton22(lv_event_t * e);
lv_obj_t * ui_ImgButton22;
lv_obj_t * ui_LabelIntelaBoxSN;
lv_obj_t * ui_LabelIntelaBoxSNValue;
lv_obj_t * ui_LabelControlHeadSN;
lv_obj_t * ui_LabelControlHeadSNValue;
void ui_event_ImgButton23(lv_event_t * e);
lv_obj_t * ui_ImgButton23;
lv_obj_t * ui_BTNRestoreDefaults;
lv_obj_t * ui_LabelControlHeadSNValue1;


// SCREEN: ui_MenuScreen4
void ui_MenuScreen4_screen_init(void);
lv_obj_t * ui_MenuScreen4;
void ui_event_ImgButtonExitMenu4(lv_event_t * e);
lv_obj_t * ui_ImgButtonExitMenu4;
void ui_event_ImgButton17(lv_event_t * e);
lv_obj_t * ui_ImgButton17;
void ui_event_ImgButton18(lv_event_t * e);
lv_obj_t * ui_ImgButton18;
void ui_event_ImgButton19(lv_event_t * e);
lv_obj_t * ui_ImgButton19;
lv_obj_t * ui_ButtonAutoTest;
lv_obj_t * ui_Label2;


// SCREEN: ui_MenuScreen5
void ui_MenuScreen5_screen_init(void);
lv_obj_t * ui_MenuScreen5;
void ui_event_ImgButtonExitMenu5(lv_event_t * e);
lv_obj_t * ui_ImgButtonExitMenu5;
void ui_event_ImgButton25(lv_event_t * e);
lv_obj_t * ui_ImgButton25;
void ui_event_ImgButton26(lv_event_t * e);
lv_obj_t * ui_ImgButton26;
lv_obj_t * ui_LabelLog1;
void ui_event_ImgButton27(lv_event_t * e);
lv_obj_t * ui_ImgButton27;
lv_obj_t * ui_LabelLog2;
lv_obj_t * ui_LabelLog3;
lv_obj_t * ui_LabelLog4;
lv_obj_t * ui_LabelLog5;
lv_obj_t * ui_LabelLog6;
lv_obj_t * ui_LabelLog7;


// SCREEN: ui_ACECONScreen
void ui_ACECONScreen_screen_init(void);
lv_obj_t * ui_ACECONScreen;
void ui_event_ImgButton14(lv_event_t * e);
lv_obj_t * ui_ImgButton14;
lv_obj_t * ui_LabelOutputs;
lv_obj_t * ui_LabelALM;
lv_obj_t * ui_LabelALMOff;
lv_obj_t * ui_LabelALMOn;
lv_obj_t * ui_SwitchALM;
lv_obj_t * ui_LabelHPS;
lv_obj_t * ui_LabelHPSOff;
lv_obj_t * ui_LabelHPSOn;
lv_obj_t * ui_SwitchHPS;
lv_obj_t * ui_LabelPPT;
lv_obj_t * ui_LabelPPTOff;
lv_obj_t * ui_LabelPPTOn;
lv_obj_t * ui_SwitchPPT;
lv_obj_t * ui_LabelPPS;
lv_obj_t * ui_SwitchPPS;
lv_obj_t * ui_LabelPPSOff;
lv_obj_t * ui_LabelPPSOn;
lv_obj_t * ui_LabelIGN;
lv_obj_t * ui_LabelIGNOff;
lv_obj_t * ui_LabelIGNOn;
lv_obj_t * ui_SwitchIGN;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;


// SCREEN: ui_ACEDATAScreen
void ui_ACEDATAScreen_screen_init(void);
lv_obj_t * ui_ACEDATAScreen;
lv_obj_t * ui_LabelOutputs1;
void ui_event_ImgButton9(lv_event_t * e);
lv_obj_t * ui_ImgButton9;
lv_obj_t * ui_LabelTemp1;
lv_obj_t * ui_LabelTemp1Val;
lv_obj_t * ui_LabelTemp2;
lv_obj_t * ui_LabelTemp2Val;
lv_obj_t * ui_LabelBattery;
lv_obj_t * ui_LabelBatteryVal;
lv_obj_t * ui_LabelEngineStatus;
lv_obj_t * ui_LabelEngineStatusVal;
lv_obj_t * ui_LabelEngineStallSensor;
lv_obj_t * ui_LabelEngineStallSensorVal;
lv_obj_t * ui_LabelEngineStallCount;
lv_obj_t * ui_LabelEngineStallCountVal;
lv_obj_t * ui_LabelAux1;
lv_obj_t * ui_LabelAux1Val;
lv_obj_t * ui_LabelAux2;
lv_obj_t * ui_LabelAux2Val;
lv_obj_t * ui_LabelK9Doors;
lv_obj_t * ui_LabelK9DoorsVal;
lv_obj_t * ui_LabelVIMModel;
lv_obj_t * ui_LabelVIMModelVal;
void ui_event_ImgButton10(lv_event_t * e);
lv_obj_t * ui_ImgButton10;


// SCREEN: ui_SerialCOMsScreen
void ui_SerialCOMsScreen_screen_init(void);
lv_obj_t * ui_SerialCOMsScreen;
lv_obj_t * ui_LabelTXData;
lv_obj_t * ui_TextAreaTXData;
lv_obj_t * ui_LabelRXData;
lv_obj_t * ui_TextAreaRXData;
void ui_event_ImgButton11(lv_event_t * e);
lv_obj_t * ui_ImgButton11;


// SCREEN: ui_PowerOffScreen
void ui_PowerOffScreen_screen_init(void);
lv_obj_t * ui_PowerOffScreen;
lv_obj_t * ui_PowerOffTextArea;


// SCREEN: ui_PowerAppliedScreen
void ui_PowerAppliedScreen_screen_init(void);
lv_obj_t * ui_PowerAppliedScreen;
lv_obj_t * ui_Image4;
lv_obj_t * ui_LabelPowerAppliedScreen;


// SCREEN: ui_MenuHelpScreen
void ui_MenuHelpScreen_screen_init(void);
lv_obj_t * ui_MenuHelpScreen;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
void ui_event_btnGoToMenu(lv_event_t * e);
lv_obj_t * ui_btnGoToMenu;
lv_obj_t * ui_Label3;


// SCREEN: ui_PowerDownScreen
void ui_PowerDownScreen_screen_init(void);
lv_obj_t * ui_PowerDownScreen;
lv_obj_t * ui_Image5;
lv_obj_t * ui_LabelPowerDownScreen;


// SCREEN: ui_SleepScreen
void ui_SleepScreen_screen_init(void);
lv_obj_t * ui_SleepScreen;
lv_obj_t * ui_SleepTextArea;


// SCREEN: ui_NoK9Screen
void ui_NoK9Screen_screen_init(void);
lv_obj_t * ui_NoK9Screen;
lv_obj_t * ui_NoK9TextArea;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_wifi_[5] = {&ui_img_wifi_0_png, &ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png, &ui_img_wifi_4_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnSpashScreenBackground(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButtonEnterMenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MenuScreen1_screen_init);
    }
}
void ui_event_ImgButtonExitMenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen2, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_MenuScreen2_screen_init);
    }
}
void ui_event_ImgButton16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen5, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_MenuScreen5_screen_init);
    }
}
void ui_event_ImgButtonExitMenu2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen3, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_MenuScreen3_screen_init);
    }
}
void ui_event_ImgButton13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen1, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_MenuScreen1_screen_init);
    }
}
void ui_event_ImgButtonExitMenu3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen4, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_MenuScreen4_screen_init);
    }
}
void ui_event_ImgButton23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen2, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_MenuScreen2_screen_init);
    }
}
void ui_event_ImgButtonExitMenu4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen5, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_MenuScreen5_screen_init);
    }
}
void ui_event_ImgButton19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen3, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_MenuScreen3_screen_init);
    }
}
void ui_event_ImgButtonExitMenu5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OperationScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OperationScreen_screen_init);
    }
}
void ui_event_ImgButton25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen1, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_MenuScreen1_screen_init);
    }
}
void ui_event_ImgButton27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen4, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_MenuScreen4_screen_init);
    }
}
void ui_event_ImgButton14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuScreen1_screen_init);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACEDATAScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ACEDATAScreen_screen_init);
    }
}
void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACECONScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ACECONScreen_screen_init);
    }
}
void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SerialCOMsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SerialCOMsScreen_screen_init);
    }
}
void ui_event_ImgButton11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ACEDATAScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ACEDATAScreen_screen_init);
    }
}
void ui_event_btnGoToMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_MenuScreen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_OperationScreen_screen_init();
    ui_MenuScreen1_screen_init();
    ui_MenuScreen2_screen_init();
    ui_MenuScreen3_screen_init();
    ui_MenuScreen4_screen_init();
    ui_MenuScreen5_screen_init();
    ui_ACECONScreen_screen_init();
    ui_ACEDATAScreen_screen_init();
    ui_SerialCOMsScreen_screen_init();
    ui_PowerOffScreen_screen_init();
    ui_PowerAppliedScreen_screen_init();
    ui_MenuHelpScreen_screen_init();
    ui_PowerDownScreen_screen_init();
    ui_SleepScreen_screen_init();
    ui_NoK9Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
