// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project_QVGA

#ifndef _SQUARELINE_PROJECT_QVGA_UI_H
#define _SQUARELINE_PROJECT_QVGA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
extern lv_obj_t * ui_SplashScreen;
void ui_event_btnSpashScreenBackground(lv_event_t * e);
extern lv_obj_t * ui_btnSpashScreenBackground;
// SCREEN: ui_OperationScreen
void ui_OperationScreen_screen_init(void);
extern lv_obj_t * ui_OperationScreen;
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_ImgButtonBattery;
extern lv_obj_t * ui_ImgButtonDoorClosed;
extern lv_obj_t * ui_ImgButtonDoorOpen;
extern lv_obj_t * ui_ImgButtonDoorPopped;
extern lv_obj_t * ui_ImgButtonDoorDisabled;
extern lv_obj_t * ui_ImgButtonKey;
extern lv_obj_t * ui_ImgButtonEngine;
extern lv_obj_t * ui_ImgButtonWiFi0;
extern lv_obj_t * ui_ImgButtonWiFi1;
extern lv_obj_t * ui_ImgButtonWiFi2;
extern lv_obj_t * ui_ImgButtonWiFi3;
extern lv_obj_t * ui_ImgButtonWiFi4;
extern lv_obj_t * ui_BtnSnooze;
extern lv_obj_t * ui_LabelAlarmText;
extern lv_obj_t * ui_LabelAlarmCounter;
extern lv_obj_t * ui_LabelLeftTemp;
extern lv_obj_t * ui_LabelRightTemp;
extern lv_obj_t * ui_LabelTempAvg;
void ui_event_ImgButtonEnterMenu1(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonEnterMenu1;
extern lv_obj_t * ui_LabelAlarmTextExtra;
// SCREEN: ui_MenuScreen1
void ui_MenuScreen1_screen_init(void);
extern lv_obj_t * ui_MenuScreen1;
void ui_event_ImgButtonExitMenu1(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonExitMenu1;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_LabelAlarmPower;
extern lv_obj_t * ui_DropdownAlarmPower;
extern lv_obj_t * ui_CheckboxAutoSnooze;
extern lv_obj_t * ui_LabelDoorPower;
extern lv_obj_t * ui_DropdownDoorPower;
extern lv_obj_t * ui_CheckboxStallMonitor;
extern lv_obj_t * ui_LabelBattVoltSet;
extern lv_obj_t * ui_LabelBattVoltSetValue;
extern lv_obj_t * ui_ImgButtonBattVoltSetDown;
extern lv_obj_t * ui_ImgButtonBattVoltSetUp;
void ui_event_ImgButton16(lv_event_t * e);
extern lv_obj_t * ui_ImgButton16;
extern lv_obj_t * ui_CheckboxAuxIn;
// SCREEN: ui_MenuScreen2
void ui_MenuScreen2_screen_init(void);
extern lv_obj_t * ui_MenuScreen2;
void ui_event_ImgButtonExitMenu2(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonExitMenu2;
void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
extern lv_obj_t * ui_LabelAlarmHotSet;
extern lv_obj_t * ui_LabelAlarmHotSetValue;
extern lv_obj_t * ui_ImgButtonHotSetDown;
extern lv_obj_t * ui_ImgButtonHotSetUp;
extern lv_obj_t * ui_LabelAlarmColdSet;
extern lv_obj_t * ui_LabelAlarmColdSetValue;
extern lv_obj_t * ui_ImgButtonColdSetDown;
extern lv_obj_t * ui_ImgButtonColdSetUp;
extern lv_obj_t * ui_CheckboxTemperatureAveraging;
extern lv_obj_t * ui_DropdownTempUnits;
extern lv_obj_t * ui_LabelTempUnits;
void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
// SCREEN: ui_MenuScreen3
void ui_MenuScreen3_screen_init(void);
extern lv_obj_t * ui_MenuScreen3;
void ui_event_ImgButtonExitMenu3(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonExitMenu3;
void ui_event_ImgButton21(lv_event_t * e);
extern lv_obj_t * ui_ImgButton21;
void ui_event_ImgButton22(lv_event_t * e);
extern lv_obj_t * ui_ImgButton22;
extern lv_obj_t * ui_LabelIntelaBoxSN;
extern lv_obj_t * ui_LabelIntelaBoxSNValue;
extern lv_obj_t * ui_LabelControlHeadSN;
extern lv_obj_t * ui_LabelControlHeadSNValue;
void ui_event_ImgButton23(lv_event_t * e);
extern lv_obj_t * ui_ImgButton23;
extern lv_obj_t * ui_BTNRestoreDefaults;
extern lv_obj_t * ui_LabelControlHeadSNValue1;
// SCREEN: ui_MenuScreen4
void ui_MenuScreen4_screen_init(void);
extern lv_obj_t * ui_MenuScreen4;
void ui_event_ImgButtonExitMenu4(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonExitMenu4;
void ui_event_ImgButton17(lv_event_t * e);
extern lv_obj_t * ui_ImgButton17;
void ui_event_ImgButton18(lv_event_t * e);
extern lv_obj_t * ui_ImgButton18;
void ui_event_ImgButton19(lv_event_t * e);
extern lv_obj_t * ui_ImgButton19;
extern lv_obj_t * ui_ButtonAutoTest;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_MenuScreen5
void ui_MenuScreen5_screen_init(void);
extern lv_obj_t * ui_MenuScreen5;
void ui_event_ImgButtonExitMenu5(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonExitMenu5;
void ui_event_ImgButton25(lv_event_t * e);
extern lv_obj_t * ui_ImgButton25;
void ui_event_ImgButton26(lv_event_t * e);
extern lv_obj_t * ui_ImgButton26;
extern lv_obj_t * ui_LabelLog1;
void ui_event_ImgButton27(lv_event_t * e);
extern lv_obj_t * ui_ImgButton27;
extern lv_obj_t * ui_LabelLog2;
extern lv_obj_t * ui_LabelLog3;
extern lv_obj_t * ui_LabelLog4;
extern lv_obj_t * ui_LabelLog5;
extern lv_obj_t * ui_LabelLog6;
extern lv_obj_t * ui_LabelLog7;
// SCREEN: ui_ACECONScreen
void ui_ACECONScreen_screen_init(void);
extern lv_obj_t * ui_ACECONScreen;
void ui_event_ImgButton14(lv_event_t * e);
extern lv_obj_t * ui_ImgButton14;
extern lv_obj_t * ui_LabelOutputs;
extern lv_obj_t * ui_LabelALM;
extern lv_obj_t * ui_LabelALMOff;
extern lv_obj_t * ui_LabelALMOn;
extern lv_obj_t * ui_SwitchALM;
extern lv_obj_t * ui_LabelHPS;
extern lv_obj_t * ui_LabelHPSOff;
extern lv_obj_t * ui_LabelHPSOn;
extern lv_obj_t * ui_SwitchHPS;
extern lv_obj_t * ui_LabelPPT;
extern lv_obj_t * ui_LabelPPTOff;
extern lv_obj_t * ui_LabelPPTOn;
extern lv_obj_t * ui_SwitchPPT;
extern lv_obj_t * ui_LabelPPS;
extern lv_obj_t * ui_SwitchPPS;
extern lv_obj_t * ui_LabelPPSOff;
extern lv_obj_t * ui_LabelPPSOn;
extern lv_obj_t * ui_LabelIGN;
extern lv_obj_t * ui_LabelIGNOff;
extern lv_obj_t * ui_LabelIGNOn;
extern lv_obj_t * ui_SwitchIGN;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// SCREEN: ui_ACEDATAScreen
void ui_ACEDATAScreen_screen_init(void);
extern lv_obj_t * ui_ACEDATAScreen;
extern lv_obj_t * ui_LabelOutputs1;
void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_LabelTemp1;
extern lv_obj_t * ui_LabelTemp1Val;
extern lv_obj_t * ui_LabelTemp2;
extern lv_obj_t * ui_LabelTemp2Val;
extern lv_obj_t * ui_LabelBattery;
extern lv_obj_t * ui_LabelBatteryVal;
extern lv_obj_t * ui_LabelEngineStatus;
extern lv_obj_t * ui_LabelEngineStatusVal;
extern lv_obj_t * ui_LabelEngineStallSensor;
extern lv_obj_t * ui_LabelEngineStallSensorVal;
extern lv_obj_t * ui_LabelEngineStallCount;
extern lv_obj_t * ui_LabelEngineStallCountVal;
extern lv_obj_t * ui_LabelAux1;
extern lv_obj_t * ui_LabelAux1Val;
extern lv_obj_t * ui_LabelAux2;
extern lv_obj_t * ui_LabelAux2Val;
extern lv_obj_t * ui_LabelK9Doors;
extern lv_obj_t * ui_LabelK9DoorsVal;
extern lv_obj_t * ui_LabelVIMModel;
extern lv_obj_t * ui_LabelVIMModelVal;
void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
// SCREEN: ui_SerialCOMsScreen
void ui_SerialCOMsScreen_screen_init(void);
extern lv_obj_t * ui_SerialCOMsScreen;
extern lv_obj_t * ui_LabelTXData;
extern lv_obj_t * ui_TextAreaTXData;
extern lv_obj_t * ui_LabelRXData;
extern lv_obj_t * ui_TextAreaRXData;
void ui_event_ImgButton11(lv_event_t * e);
extern lv_obj_t * ui_ImgButton11;
// SCREEN: ui_PowerOffScreen
void ui_PowerOffScreen_screen_init(void);
extern lv_obj_t * ui_PowerOffScreen;
extern lv_obj_t * ui_PowerOffTextArea;
// SCREEN: ui_PowerAppliedScreen
void ui_PowerAppliedScreen_screen_init(void);
extern lv_obj_t * ui_PowerAppliedScreen;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_LabelPowerAppliedScreen;
// SCREEN: ui_MenuHelpScreen
void ui_MenuHelpScreen_screen_init(void);
extern lv_obj_t * ui_MenuHelpScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
void ui_event_btnGoToMenu(lv_event_t * e);
extern lv_obj_t * ui_btnGoToMenu;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_PowerDownScreen
void ui_PowerDownScreen_screen_init(void);
extern lv_obj_t * ui_PowerDownScreen;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_LabelPowerDownScreen;
// SCREEN: ui_SleepScreen
void ui_SleepScreen_screen_init(void);
extern lv_obj_t * ui_SleepScreen;
extern lv_obj_t * ui_SleepTextArea;
// SCREEN: ui_NoK9Screen
void ui_NoK9Screen_screen_init(void);
extern lv_obj_t * ui_NoK9Screen;
extern lv_obj_t * ui_NoK9TextArea;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_acek9logo_png);    // assets\ACEK9Logo.png
LV_IMG_DECLARE(ui_img_arrowlefticon_png);    // assets\ArrowLeftIcon.png
LV_IMG_DECLARE(ui_img_arrowiconblank_png);    // assets\ArrowIconBlank.png
LV_IMG_DECLARE(ui_img_batteryenabledicon_png);    // assets\BatteryEnabledIcon.png
LV_IMG_DECLARE(ui_img_batterydisabledicon_png);    // assets\BatteryDisabledIcon.png
LV_IMG_DECLARE(ui_img_cardoorenabledicon_png);    // assets\CarDoorEnabledIcon.png
LV_IMG_DECLARE(ui_img_cardooropenicon_png);    // assets\CarDoorOpenIcon.png
LV_IMG_DECLARE(ui_img_cardoorpoppedicon_png);    // assets\CarDoorPoppedIcon.png
LV_IMG_DECLARE(ui_img_cardoordisabledicon_png);    // assets\CarDoorDisabledIcon.png
LV_IMG_DECLARE(ui_img_keyenabledicon_png);    // assets\KeyEnabledIcon.png
LV_IMG_DECLARE(ui_img_keyicon_png);    // assets\KeyIcon.png
LV_IMG_DECLARE(ui_img_engineenabledicon_png);    // assets\EngineEnabledIcon.png
LV_IMG_DECLARE(ui_img_enginedisabledicon_png);    // assets\EngineDisabledIcon.png
LV_IMG_DECLARE(ui_img_wifi_0_png);    // assets\WiFi 0.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets\WiFi 1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets\WiFi 2.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets\WiFi 3.png
LV_IMG_DECLARE(ui_img_wifi_4_png);    // assets\WiFi 4.png
LV_IMG_DECLARE(ui_img_arrowrighticon_png);    // assets\ArrowRightIcon.png
LV_IMG_DECLARE(ui_img_arrowdownicon_png);    // assets\ArrowDownIcon.png
LV_IMG_DECLARE(ui_img_arrowdowniconsmall_png);    // assets\ArrowDownIconSmall.png
LV_IMG_DECLARE(ui_img_arrowupiconsmall_png);    // assets\ArrowUpIconSmall.png
LV_IMG_DECLARE(ui_img_arrowupicon_png);    // assets\ArrowUpIcon.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
